### ISSUE TITLE
Problem with twig-view being initialized before

### ISSUE THREAD

**Issue by kalvn** [akrabat/proxy-detection-middleware#5]
I'm using Twig-View behind a proxy. Therefore, I use your middleware in order for extensions `base_url` and `path_for` to work properly.
But as the renderer seems to be initialized before the middleware, it uses the initial Uri object which is not modified by the middleware yet (`getUri()` below).

``` php
$container['renderer'] = function ($c) {
    $settings = $c->get('settings')['renderer'];
    $view = new Slim\Views\Twig($settings['template_path'], [
        'cache' => $settings['cache_path'],
        'auto_reload' => true
    ]);
    $view->addExtension(new Slim\Views\TwigExtension(
        $c['router'],
        $c['request']->getUri()
    ));

    return $view;
};
```

Consequently my paths are generated in http instead of https.
Any solution for this?

As it concerns twig-view as well, I didn't know where to open the issue, I hope it's not a problem.

**Comment by pfyod** [comment]
@kalvn: can use this middleware as a workaround:
```
class UpdateTwigBaseUrlMiddleware {
    private $twig;
    public function __construct(Twig $twig) {
        $this->twig = $twig;
    }
    public function __invoke($request, $response, $next) {
        $this->twig->getEnvironment()->getExtension('slim')->setBaseUrl($request->getUri());
        return $next($request, $response);
    }
}
```

**Comment by kalvn** [comment]
I'll give a try, thanks :)
